// Canonicalize ims-website.pages.dev -> innovativemedicalstaffing.com AND
// apply the project security headers.
//
// Cloudflare Pages _redirects is path-only and cannot do host-aware redirects
// (https://developers.cloudflare.com/pages/configuration/redirects/), so a
// Pages Function middleware is required to canonicalize the duplicate origin.
//
// Cloudflare also documents that public/_headers does NOT apply to responses
// generated by Pages Functions
// (https://developers.cloudflare.com/pages/configuration/headers/) — and a
// root /functions/_middleware.js runs on every request, so every response is
// Function-generated. Security headers are therefore applied here directly.
// public/_headers is kept as a redundant fallback in case this middleware is
// ever removed; for live responses, this file is authoritative.
//
// Exact-match on the canonical .pages.dev hostname only — preview deploys
// (<hash>.ims-website.pages.dev, <branch>.ims-website.pages.dev) keep their
// own hostnames so the preview workflow is unaffected.
const SECURITY_HEADERS = {
  "X-Robots-Tag": "noindex, nofollow",
  "Strict-Transport-Security": "max-age=15768000; includeSubDomains",
  // form-action 'self' (was 'none'): the Get In Touch form POSTs same-origin
  // to /api/contact. No script-src is added — the site ships zero JS (the
  // result UX is a server 303 to the static /thank-you and /couldnt-send
  // pages). fonts.googleapis.com in style-src + fonts.gstatic.com in font-src
  // are required by the Belleval @import (Anton/Fraunces/Hanken) in ims.css;
  // self-hosting the woff2 and dropping back to 'self' is the permanent-site
  // hardening. Policy stays maximally strict otherwise.
  "Content-Security-Policy":
    "default-src 'none'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'",
  "Permissions-Policy":
    "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
};

const withSecurityHeaders = (response) => {
  const cloned = new Response(response.body, response);
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    cloned.headers.set(name, value);
  }
  return cloned;
};

export const onRequest = async ({ request, next }) => {
  const url = new URL(request.url);
  if (url.hostname === "ims-website.pages.dev") {
    url.hostname = "innovativemedicalstaffing.com";
    url.protocol = "https:";
    return withSecurityHeaders(Response.redirect(url.toString(), 301));
  }
  return withSecurityHeaders(await next());
};
