/**
 * LocumSmart webhook receiver — POST /api/locumsmart-webhook
 *
 * Auth: bare-token-in-body via constant-time compare against
 * LOCUMSMART_WEBHOOK_SECRET (the Webhook Key auto-generated by LS when
 * Zach creates the "Website" subscription). NOT HMAC.
 *
 * Dispatch: body.operation drives status — Receive/Update keep status='active',
 * Cancel/Archive flip to 'archived' so /jobs auto-takedown when LS marks an
 * assignment closed/canceled.
 *
 * Idempotency: UPSERT on id (LS-provided assignmentId UUID). LS retries are
 * safe — re-applying the same payload writes the same row.
 */

import type { APIRoute } from 'astro';
import { createClient } from '@supabase/supabase-js';
import {
  constantTimeEquals,
  mapToImsJobsRow,
  validatePayloadShape,
  type LSWebhookPayload,
} from '../../lib/locumsmart-webhook-logic';

export const prerender = false;

interface PagesEnv {
  SUPABASE_URL?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  LOCUMSMART_WEBHOOK_SECRET?: string;
}

function readEnv(locals: App.Locals): PagesEnv {
  // Cloudflare Pages exposes env at locals.runtime.env when @astrojs/cloudflare
  // adapter is active. In a dev/test context locals.runtime is undefined and
  // we fall back to import.meta.env so misconfiguration fails as 500 rather
  // than as a runtime crash.
  const cf = (locals as { runtime?: { env?: PagesEnv } }).runtime?.env;
  if (cf) return cf;
  return {
    SUPABASE_URL: import.meta.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: import.meta.env.SUPABASE_SERVICE_ROLE_KEY,
    LOCUMSMART_WEBHOOK_SECRET: import.meta.env.LOCUMSMART_WEBHOOK_SECRET,
  };
}

export const POST: APIRoute = async ({ request, locals }) => {
  const env = readEnv(locals);

  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY || !env.LOCUMSMART_WEBHOOK_SECRET) {
    // Intentional 500 (not 401) for misconfig: LS retries 5xx but not 4xx, so
    // a temporary missing-secret state during deploy gets healed by the next
    // retry once the operator sets the env var. The body shape difference vs.
    // the 401 path is a deployment-state oracle in theory, but the receiver
    // values resilience over stealth (LS is the only legitimate caller anyway,
    // bounded by IP + the Webhook Key).
    console.error('[ls-webhook] env misconfigured');
    return new Response('Server misconfigured', { status: 500 });
  }

  let raw: unknown;
  try {
    raw = await request.json();
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  const shape = validatePayloadShape(raw);
  if (!shape.ok) {
    console.warn('[ls-webhook] shape invalid:', shape.reason);
    return new Response('Bad payload', { status: 400 });
  }
  const payload = raw as LSWebhookPayload;

  if (!constantTimeEquals(payload.key, env.LOCUMSMART_WEBHOOK_SECRET)) {
    console.warn('[ls-webhook] unauthorized — token mismatch for', payload.assignmentId);
    return new Response('Unauthorized', { status: 401 });
  }

  const row = mapToImsJobsRow(payload);

  const supabase = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // Atomic conditional upsert. Try INSERT first; on PK conflict (code 23505)
  // fall through to a conditional UPDATE whose WHERE clause encodes the
  // freshness rules. Postgres row-level locking on UPDATE serializes
  // concurrent writes against the same id — an older event whose WHERE
  // clause does not match simply no-ops, so a delayed stale event cannot
  // overwrite a later cancel. The freshness rules mirror evaluateFreshness
  // in src/lib/locumsmart-webhook-logic.ts (kept as the unit-tested spec):
  //   - apply when incoming ls_last_modified > stored
  //   - apply when same-timestamp AND incoming archived AND stored active
  //     (terminal events dominate ties)
  //   - skip when incoming < stored (stale)
  //   - skip same-timestamp ties for active-incoming-vs-archived-stored
  const { error: insertErr } = await supabase
    .from('ims_jobs')
    .insert(row);

  if (!insertErr) {
    console.log('[ls-webhook] inserted:', payload.assignmentId, payload.operation, '->', row.status);
    return new Response('OK', { status: 200 });
  }

  // Postgres unique_violation = '23505'. Two unique constraints exist on
  // ims_jobs: ims_jobs_pkey (on id) and ims_jobs_assignment_number_key
  // (on assignment_number). Only fall through to UPDATE when the conflict
  // is on the PK — a conflict on assignment_number means LS sent the same
  // assignmentNumber with a different assignmentId (would be an integrity
  // problem worth surfacing as 500, not silently no-opping as "stale").
  if (insertErr.code !== '23505') {
    console.error('[ls-webhook] insert failed:', payload.assignmentId, insertErr.message);
    return new Response('Database error', { status: 500 });
  }
  if (!insertErr.message.includes('ims_jobs_pkey')) {
    console.error('[ls-webhook] insert failed (non-pk unique violation):', payload.assignmentId, insertErr.message);
    return new Response('Database error', { status: 500 });
  }

  // Existing row — conditional UPDATE. Normalize the incoming timestamp to a
  // strict ISO string before injecting into the PostgREST .or() filter so LS
  // format drift (fractional seconds, timezone offsets, etc.) cannot break
  // the filter grammar. Date.prototype.toISOString always emits the
  // YYYY-MM-DDTHH:mm:ss.sssZ shape which is unambiguous for both PostgREST
  // and Postgres timestamptz parsing.
  const rawLm = row.ls_last_modified;
  const parsedLm = rawLm ? new Date(rawLm) : null;
  const incomingLm = parsedLm && !isNaN(parsedLm.getTime()) ? parsedLm.toISOString() : null;

  let updateBuilder = supabase
    .from('ims_jobs')
    .update(row, { count: 'exact' })
    .eq('id', payload.assignmentId);

  if (incomingLm) {
    const orFilters = [
      'ls_last_modified.is.null',
      `ls_last_modified.lt.${incomingLm}`,
    ];
    if (row.status === 'archived') {
      // Same-timestamp tie: archived overwrites active.
      orFilters.push(`and(ls_last_modified.eq.${incomingLm},status.eq.active)`);
    }
    updateBuilder = updateBuilder.or(orFilters.join(','));
  }
  // If incoming has no ls_last_modified (or it failed to parse) we apply
  // unconditionally rather than drop the event silently.

  const { error: updateErr, count } = await updateBuilder;

  if (updateErr) {
    console.error('[ls-webhook] update failed:', payload.assignmentId, updateErr.message);
    return new Response('Database error', { status: 500 });
  }

  if (count === 0) {
    console.warn('[ls-webhook] event skipped (atomic freshness guard):', payload.assignmentId, payload.operation);
    return new Response('OK (skipped: stale-or-tie)', { status: 200 });
  }

  console.log('[ls-webhook] updated:', payload.assignmentId, payload.operation, '->', row.status);
  return new Response('OK', { status: 200 });
};

// HEAD/GET return 405 so health probes get a quick rejection. LS only sends
// POST so anything else is either misconfiguration or a probe.
export const GET: APIRoute = () => new Response('Method Not Allowed', { status: 405 });
export const HEAD: APIRoute = () => new Response(null, { status: 405 });
